### ISSUE TITLE
Critical Error on Vercel (upgrading from 0.6.2 to 0.9.0)

### ISSUE THREAD

**Issue by Kulcanhez** [mhayes/vue-twentytwenty#13]
Hello @mhayes 😄 really thank you for all the updates and care to this project.

I've been using for the last weeks your plugin and everything was working great. Today I upgraded from 0.6.2 to 0.9.0 and I have a critical error on Vercel build.

![Vercel Critical Error](https://user-images.githubusercontent.com/5109593/82909995-f0463b00-9f61-11ea-92f3-88bfcc4d942c.jpg)

Thank you! 🥇

**Comment by mhayes** [comment]
@Kulcanhez Looks like this change is related to disabling CSS extraction (so users don't have to download the CSS file) here https://github.com/mhayes/vue-twentytwenty/blob/master/vue.config.js#L2. Thinking that it might be best to revert that change and push out `0.10.0` ...

**Comment by Kulcanhez** [comment]
> @Kulcanhez Looks like this change is related to disabling CSS extraction (so users don't have to download the CSS file) here [/vue.config.js@`master`#L2](https://github.com/mhayes/vue-twentytwenty/blob/master/vue.config.js#L2) [](/mhayes/vue-twentytwenty/blob/HEAD@{2020-05-26T14:35:29Z}/vue.config.js#L2). Thinking that it might be best to revert that change and push out `0.10.0` ...

I can `gridsome develop` and `gridsome build` on my computer but Vercel doesn't seem to like it. Not sure about Netlify or others.

**Comment by mhayes** [comment]
@Kulcanhez can you give this version a try:

https://github.com/mhayes/vue-twentytwenty/releases/tag/v0.10.1

**Comment by Kulcanhez** [comment]
> @Kulcanhez can you give this version a try:
> 
> [`v0.10.1` (release)](https://github.com/mhayes/vue-twentytwenty/releases/tag/v0.10.1)

It's working. Thank youuu! 🙂
