### ISSUE TITLE
On touch events, handle keeps sliding even if finger leaves area.

### ISSUE THREAD

**Issue by beacrea** [mhayes/vue-twentytwenty#3]
If a user clicks into the comparison frame on a mobile device, the touch event is captured there, but doesn't end until the user clicks the frame again.

Basically, touchup isn't being registered properly.

**Comment by beacrea** [comment]
I figured out what was happening. 'touchup' isn't a recognized event, rather 'touchend' is the event that it should be listening. In the component file, this section should now look like this:

```
mounted () {
  document.addEventListener("touchmove", this.moveSlide)
  document.addEventListener("touchend", this.endSlide)
  document.addEventListener("mousemove", this.moveSlide)
  document.addEventListener("mouseup", this.endSlide)
  window.addEventListener("resize", this.resize)
},
beforeDestroy () {
  document.removeEventListener("touchmove", this.moveSlide)
  document.removeEventListener("touchend", this.endSlide)
  document.removeEventListener("mousemove", this.moveSlide)
  document.removeEventListener("mouseup", this.endSlide)
  window.removeEventListener("resize", this.resize)
}
```

**Comment by mhayes** [comment]
Thanks for pointing out this issue @beacrea, can't believe I missed that before. You'll see this change reflected in `vue-twentytwenty@0.6.1`.

Cheers!
